<center> <h1> Sudoku Solver <br> </h1> </center>
This notebook has a function written with a driver code to solve sudoku puzzles. The input is a tedious way of entering 9x9 Matrix row-wise with 0 entered for positions to be filled by the solver. The solver works based on recursion and uses a separate checker function so that the filled 9x9 grid follows the rules - Each column, each row, and each of the nine 3x3 subgrids (also called boxes) contain all of the digits exactly once.<br> 
<h3> Date Revised: July-8th 2024 </h3>
<h3> Version: 1.1 </h3>
<br>
Version Log:<br>
1.0 - Initial Commit to github<br>
1.1 - Input Verification<br>

In [1]:
# Packages 
import numpy as np
import datetime
%load_ext memory_profiler

In [2]:
def sudoku_input():
    ''' Gets input of sudoku 9x9 Matrix style with inputs in a row format'''
    R = 9
    C = 9
    grid = []
    
    print("Enter the Sudoku Row-wise (values should be between 0 and 9 inclusive):")
    for i in range(R):
        row = []
        for j in range(C):
            while True:
                try:
                    value = int(input(f"Enter value for row {i+1}, column {j+1}: "))
                    if 0 <= value <= 9:
                        break  # Valid input, exit the loop
                    else:
                        print("Value must be between 0 and 9 inclusive. Please try again.")
                except ValueError:
                    print("Invalid input. Please enter a number between 0 and 9.")
            
            row.append(value)
        grid.append(row)
    # Print the matrix
    print("\nThe Sudoku Matrix:")
    print(np.matrix(grid))
    # Check if everything is not zero
    flag = 0
    if all(value == 0 for row in grid for value in row):
        print("All cells in the Sudoku grid are filled with zero")
        flag = 1    
    return grid, flag


In [3]:
def possible_combination_checker(row,col,num):
    ''' Checks the number entered in the position according to the rules rules simultaneously'''
    global grid
    # Checking if the number occurs in the row once
    for i in range(0,9):
        if grid[row][i] == num:
            return False
    # Checking if the number occurs in the column once
        if grid[i][col] == num:
            return False
    # Checking if the number occurs in the box once
    l = (row//3) * 3# using Floor division to get an integer value
    m = (col//3) * 3
    
    for i in range(0,3):
        for j in range(0,3):
            if(grid[l+i][m+j]==num):
                return False
    return True

In [4]:
def solve_sudoku():
    ''' Fills the number 1-9 in the position and calls the checker to verify the input'''
    global grid
    for row in range(0,9):
        for col in range(0,9):
            if grid[row][col] == 0:
                for num in range(1,10):
                    if possible_combination_checker(row,col,num):
                        grid[row][col] = num
                        solve_sudoku()
                        grid[row][col] = 0
                return 
    print(np.matrix(grid))

In [5]:
# Call the functions to solve the sudoku
grid, flag = sudoku_input()

Enter the Sudoku Row-wise (values should be between 0 and 9 inclusive):


Enter value for row 1, column 1:  0
Enter value for row 1, column 2:  0
Enter value for row 1, column 3:  0
Enter value for row 1, column 4:  2
Enter value for row 1, column 5:  8
Enter value for row 1, column 6:  0
Enter value for row 1, column 7:  0
Enter value for row 1, column 8:  0
Enter value for row 1, column 9:  0
Enter value for row 2, column 1:  06
Enter value for row 2, column 2:  0
Enter value for row 2, column 3:  0
Enter value for row 2, column 4:  0
Enter value for row 2, column 5:  0
Enter value for row 2, column 6:  0
Enter value for row 2, column 7:  0
Enter value for row 2, column 8:  0
Enter value for row 2, column 9:  0
Enter value for row 3, column 1:  0
Enter value for row 3, column 2:  3
Enter value for row 3, column 3:  9
Enter value for row 3, column 4:  4
Enter value for row 3, column 5:  6
Enter value for row 3, column 6:  0
Enter value for row 3, column 7:  2
Enter value for row 3, column 8:  1
Enter value for row 3, column 9:  0
Enter value for row 4, colu


The Sudoku Matrix:
[[0 0 0 2 8 0 0 0 0]
 [6 0 0 0 0 0 0 0 0]
 [0 3 9 4 6 0 2 1 0]
 [0 5 0 0 9 0 0 0 7]
 [0 9 0 7 5 6 0 3 0]
 [3 0 0 0 2 0 0 5 0]
 [0 4 7 0 1 5 8 9 0]
 [0 0 0 0 0 0 0 0 5]
 [0 0 0 0 7 8 0 0 0]]


In [6]:
start_time = datetime.datetime.now()
if flag != 1:
    solve_sudoku()
    end_time = datetime.datetime.now()
    total_time = (end_time-start_time).total_seconds()
    print(f"Sudoku solved in: {total_time:.2f} seconds")
else:
    print("Sudoku Solver Terminated as inputs are trivial")

[[7 1 4 2 8 9 5 6 3]
 [6 2 8 5 3 1 7 4 9]
 [5 3 9 4 6 7 2 1 8]
 [4 5 2 1 9 3 6 8 7]
 [8 9 1 7 5 6 4 3 2]
 [3 7 6 8 2 4 9 5 1]
 [2 4 7 3 1 5 8 9 6]
 [9 8 3 6 4 2 1 7 5]
 [1 6 5 9 7 8 3 2 4]]
Sudoku solved in: 0.04 seconds


In [8]:
# Memory Allocation
if (flag!= 1): 
    %memit solve_sudoku()


[[7 1 4 2 8 9 5 6 3]
 [6 2 8 5 3 1 7 4 9]
 [5 3 9 4 6 7 2 1 8]
 [4 5 2 1 9 3 6 8 7]
 [8 9 1 7 5 6 4 3 2]
 [3 7 6 8 2 4 9 5 1]
 [2 4 7 3 1 5 8 9 6]
 [9 8 3 6 4 2 1 7 5]
 [1 6 5 9 7 8 3 2 4]]
peak memory: 81.75 MiB, increment: 0.31 MiB
